# Generated by Django 5.0.9 on 2025-10-11 01:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_type', models.CharField(max_length=20)),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Session',
                'verbose_name_plural': 'Trading Sessions',
                'db_table': 'trading_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BotTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(help_text='Trading pair (e.g., BTC/USDT, ETH/USDT)', max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-08)])),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-08)])),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0.0, help_text='Profit/Loss in EUR', max_digits=15)),
                ('profit_loss_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_open', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot Trade',
                'verbose_name_plural': 'Bot Trades',
                'db_table': 'bot_trades',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['user', 'is_open'], name='bot_trades_user_id_ca6a8b_idx'), models.Index(fields=['symbol', 'opened_at'], name='bot_trades_symbol_1409ca_idx')],
            },
        ),
    ]
