# Generated by Django 5.0.9 on 2025-11-15 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_alter_bottrade_entry_price_alter_bottrade_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bottrade",
            index=models.Index(
                fields=["user", "-opened_at"], name="bot_trades_user_id_1ccfae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradingsession",
            index=models.Index(
                fields=["user", "is_active"], name="trading_ses_user_id_377779_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradingsession",
            index=models.Index(
                fields=["user", "-ended_at"], name="trading_ses_user_id_f40954_idx"
            ),
        ),
    ]
