# Generated by Django 5.0.9 on 2025-10-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bot_active',
            field=models.BooleanField(default=False, help_text='Whether the trading bot is currently active'),
        ),
    ]
