# Generated by Django 5.0.9 on 2025-10-17 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_bot_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_bot_active',
        ),
    ]
