# Generated by Django 5.0.9 on 2025-11-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_date_of_birth_user_first_name_user_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet_address",
            field=models.CharField(
                blank=True,
                help_text="Cryptocurrency wallet address for withdrawals",
                max_length=255,
            ),
        ),
    ]
