# Generated by Django 5.0.9 on 2025-11-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_wallet_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_bot_enabled",
            field=models.BooleanField(
                default=False, help_text="Master switch to enable/disable bot trading"
            ),
        ),
    ]
