# Generated by Django 5.0.9 on 2025-10-11 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('USDT_TRC20', 'USDT (TRC20)'), ('USDT_ERC20', 'USDT (ERC20)'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20)),
                ('wallet_address', models.CharField(blank=True, help_text='Crypto wallet address', max_length=255)),
                ('bank_details', models.TextField(blank=True, help_text='Bank account details (for bank transfers)')),
                ('network', models.CharField(blank=True, help_text='Blockchain network (e.g., TRC20, ERC20)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Show this payment method to users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payment_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Details',
                'verbose_name_plural': 'Payment Details',
                'db_table': 'payment_details',
                'ordering': ['-created_at'],
            },
        ),
    ]
