# Generated by Django 5.0.9 on 2025-10-14 00:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Открытый'), ('in_progress', 'В обработке'), ('closed', 'Закрытый')], default='open', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Тема обращения', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_chats', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Chat',
                'verbose_name_plural': 'Support Chats',
                'db_table': 'support_chats',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, help_text='Attached file (receipt, screenshot, etc.)', null=True, upload_to='support/%Y/%m/%d/')),
                ('is_from_admin', models.BooleanField(default=False, help_text='True if message is from admin/support')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Message',
                'verbose_name_plural': 'Support Messages',
                'db_table': 'support_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportchat',
            index=models.Index(fields=['user', '-updated_at'], name='support_cha_user_id_414814_idx'),
        ),
        migrations.AddIndex(
            model_name='supportchat',
            index=models.Index(fields=['status', '-updated_at'], name='support_cha_status_bc39bc_idx'),
        ),
        migrations.AddIndex(
            model_name='supportchat',
            index=models.Index(fields=['assigned_admin', '-updated_at'], name='support_cha_assigne_0f16af_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['chat', 'created_at'], name='support_mes_chat_id_8f1c48_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['is_read', 'is_from_admin'], name='support_mes_is_read_b537a5_idx'),
        ),
    ]
